name: 02-weather-api

services:
  postgres:
    image: postgres
    container_name: 02-weather-api-postgres
    environment:
      POSTGRES_DB: 02-weather-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - 02-weather-api_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  redis:
    image: redis:7.4-alpine
    container_name: 02-weather-api-redis
    ports:
      - "6379:6379"
    volumes:
      - 02-weather-api_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  02-weather-api_postgres_data:
  02-weather-api_redis_data:
